In [1]:
from typing import List
from typing import Union

import numpy as np
from IPython.display import display
from matplotlib import pyplot as plt
from PIL import Image
from urllib.request import urlopen
from scipy.spatial import distance

## Vector

In [2]:
u = np.array([1, 2, 3])
print(u.shape)

(3,)


In [4]:
# Norms
def norm(
    vector: Union[List[float], np.ndarray], 
    order: int = 2
) -> float:
    """Calculate the L-order norm."""
    value = (sum([abs(x)**order for x in vector]))**(1 / order)
    return value

In [5]:
for order in range(1, 4):
    print(f"The L-{order} norm is:                    ", norm(vector=u, order=order))
    print(f"The L-{order} norm calculated by numpy is:", np.linalg.norm(x=u, ord=order))
    print()

The L-1 norm is:                     6.0
The L-1 norm calculated by numpy is: 6.0

The L-2 norm is:                     3.7416573867739413
The L-2 norm calculated by numpy is: 3.7416573867739413

The L-3 norm is:                     3.3019272488946263
The L-3 norm calculated by numpy is: 3.3019272488946263



In [6]:
# Dot product
def dot_product(
    u: Union[List[float], np.ndarray],
    v: Union[List[float], np.ndarray]
) -> float:
    """Calcuate the dot- (inner-) product between two vectors."""
    value = sum([x * y for x, y in zip(u, v)])
    return value

In [7]:
v = np.array([4, 5, 6])

print(dot_product(u, v))
print(np.dot(u, v))
print(u @ v.T)  # short-hand for matrix multiplication

32
32
32


In [8]:
# Distance
print(u - v)
print(norm(u - v))
print(distance.euclidean(u, v))

[-3 -3 -3]
5.196152422706632
5.196152422706632


In [9]:
def cosine_distance(
    u: Union[List[float], np.ndarray],
    v: Union[List[float], np.ndarray]
) -> float:
    """Calculate the cosine distance between two vectors."""
    value = dot_product(u, v) / (norm(u) * norm(v))
    return 1 - value

print(cosine_distance(u, v))
print(distance.cosine(u, v))

0.025368153802923787
0.0253681538029239


## Matrix

In [10]:
A = np.array([
  [1, 2],
  [3, 4],  
])
print(A.shape)

(2, 2)


In [11]:
B = np.array([
  [5, 6],
  [7, 8],  
])

A + B

array([[ 6,  8],
       [10, 12]])

In [12]:
# broadcasting
A + 3

array([[4, 5],
       [6, 7]])

In [13]:
A * 3

array([[ 3,  6],
       [ 9, 12]])

In [14]:
# multiplication
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
])
B = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(A.shape, B.shape)

(4, 2) (2, 3)


In [15]:
np.matmul(A, B)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [16]:
A @ B

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [17]:
# transpose
print(A)
print(A.T)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 3 5 7]
 [2 4 6 8]]


In [18]:
# trace
print(np.trace(A @ A.T))
print(np.trace(A.T @ A))

204
204


In [19]:
# determinant
print(np.linalg.det(A @ A.T))
print(np.linalg.det(A.T @ A))

0.0
79.99999999999976


In [20]:
# identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# inverse
X = A.T @ A
print(X)
np.linalg.inv(X)

[[ 84 100]
 [100 120]]


array([[ 1.5 , -1.25],
       [-1.25,  1.05]])

In [22]:
Y = A @ A.T

# this will fail
np.linalg.inv(Y)

LinAlgError: Singular matrix

In [24]:
# pseudo-inverse
np.linalg.pinv(Y)

array([[ 1.7225,  0.8825,  0.0425, -0.7975],
       [ 0.8825,  0.4525,  0.0225, -0.4075],
       [ 0.0425,  0.0225,  0.0025, -0.0175],
       [-0.7975, -0.4075, -0.0175,  0.3725]])

In [25]:
np.linalg.pinv(Y) @ Y

array([[ 0.7,  0.4,  0.1, -0.2],
       [ 0.4,  0.3,  0.2,  0.1],
       [ 0.1,  0.2,  0.3,  0.4],
       [-0.2,  0.1,  0.4,  0.7]])

In [26]:
# rank
print(X.shape)
print(np.linalg.matrix_rank(X))

(2, 2)
2


In [27]:
print(Y.shape)
print(np.linalg.matrix_rank(Y))

(4, 4)
2


## Eigenvalues and eigenvectors

In [28]:
w, v = np.linalg.eig(X)

In [29]:
print(w)
print(v)

[  0.39291363 203.60708637]
[[-0.7671874  -0.64142303]
 [ 0.64142303 -0.7671874 ]]


In [30]:
print(X @ v[:, 0])

[-0.30143839  0.25202385]


In [31]:
w[0] * v[:, 0]

array([-0.30143839,  0.25202385])

## SVD

In [32]:
# SVD
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

U, Sigma, V = np.linalg.svd(A)
V = V.T
print("U:\n", U)
print("Sigma:\n", Sigma)
print("V:\n", V)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma:
 [9.52551809 0.51430058]
V:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [33]:
# recreate the original matrix
# we need to turn the ``Sigma`` to a ndarray of the proper shape
U @ np.insert(np.diag(Sigma), len(Sigma), [0, 0], 0) @ V.T

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [34]:
# Create the partial matrices
US = U @ np.insert(np.diag(Sigma), len(Sigma), [0, 0], 0)
US

array([[-2.18941839,  0.45436451],
       [-4.99846626,  0.12383458],
       [-7.80751414, -0.20669536]])

In [35]:
# partial matrix 1
np.matrix(US[:, 0]).T @ np.matrix(V[:, 0])

matrix([[1.35662819, 1.71846235],
        [3.09719707, 3.92326845],
        [4.83776596, 6.12807454]])

In [36]:
# partial matrix 2
np.matrix(US[:, 1]).T @ np.matrix(V[:, 1])

matrix([[-0.35662819,  0.28153765],
        [-0.09719707,  0.07673155],
        [ 0.16223404, -0.12807454]])

In [ ]:
# Image compression
FIGURE_SIZE = (10, 10)
plt.gray()

original = Image.open(urlopen("https://github.com/changyaochen/MECE4520/raw/master/data/leena.png"))
plt.figure(figsize=FIGURE_SIZE)
plt.imshow(original, interpolation="none")

In [ ]:
original_data = np.array(original)
print(original_data.shape)
original_data

In [ ]:
U, Sigma, V = np.linalg.svd(original_data)
V = V.T

In [ ]:
k = 20  # Number of principle components to keep

U_reduced = U[:, 0:k]
V_reduced = V[:, 0:k]
Sigma_reduced = np.diag(Sigma[:k])

In [ ]:
compressed = U_reduced @ Sigma_reduced @ V_reduced.T

plt.figure(figsize=FIGURE_SIZE)
plt.imshow(compressed, interpolation="none")